# Generated by Django 5.0.6 on 2024-06-23 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_practice', models.DateField()),
                ('vet_speciality', models.CharField(choices=[('SA', 'SMALL ANIMALS'), ('LA', 'LARGE ANIMALS'), ('BIRDS', 'POULTRY'), ('SA && LA', 'SMALL ANIMALS AND LARGE ANIMALS')], max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
