# Generated by Django 5.0.6 on 2024-06-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='county',
            field=models.CharField(choices=[('MOMBASA', 'MOMBASA'), ('NAIROBI', 'NAIROBI'), ('TRANS-NZOIA', 'TRANSNZOIA')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.CharField(choices=[('KITALE', 'KITALE'), ('ELDORET', 'ELDORET')], max_length=20, null=True),
        ),
    ]
