# Generated by Django 5.0.6 on 2024-06-24 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_vetcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vetcomment',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='vetcomment',
            name='is_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vetcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vetcomment'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('correspondents', models.ManyToManyField(to='base.vetcomment')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vet')),
            ],
        ),
    ]
