# Generated by Django 5.0.6 on 2024-06-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_vetcomment_options_vetcomment_is_consultation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
