# Generated by Django 5.0.6 on 2024-06-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_consultation_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='correspondents',
            field=models.ManyToManyField(blank=True, to='base.vetcomment'),
        ),
    ]
