# Generated by Django 5.0.6 on 2024-06-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_consultation_correspondents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='vet',
            options={'ordering': ['-consultations']},
        ),
        migrations.AddField(
            model_name='vet',
            name='consultations',
            field=models.IntegerField(default=0),
        ),
    ]
