# Generated by Django 5.0.6 on 2024-06-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_vet_options_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='venue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
