# Generated by Django 5.0.6 on 2024-06-24 15:02

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_appointment_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='scheduled_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_date',
            field=models.DateField(validators=[base.validators.validate_appointment_date]),
        ),
    ]
