# Generated by Django 5.0.6 on 2024-06-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_appointment_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vet',
            options={'ordering': ['-successfull_consultations', '-consultations', '-start_practice']},
        ),
        migrations.AddField(
            model_name='consultation',
            name='client_satisfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet',
            name='successfull_consultations',
            field=models.IntegerField(default=0),
        ),
    ]
