# Generated by Django 5.0.6 on 2024-06-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_vet_options_consultation_client_satisfied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetcomment',
            name='is_satisfaction_comment',
            field=models.BooleanField(default=False),
        ),
    ]
