# Generated by Django 5.0.6 on 2024-06-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_vet_options_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='scheduled_time',
            new_name='scheduled_time_from',
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_time_to',
            field=models.TimeField(null=True),
        ),
    ]
