# Generated by Django 5.0.6 on 2024-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_scheduled_time_appointment_scheduled_time_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='licence_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet',
            name='licence_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
