# Generated by Django 5.0.6 on 2024-06-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_consultation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='client_left_comment',
            field=models.BooleanField(default=False),
        ),
    ]
