# Generated by Django 5.0.6 on 2024-06-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_consultation_client_left_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_on',
            field=models.BooleanField(default=True),
        ),
    ]
