# Generated by Django 5.0.6 on 2024-06-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['scheduled_date', 'scheduled_time_from']},
        ),
        migrations.AddField(
            model_name='consultation',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='breed',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='history_of_illness',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='sex',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=2, null=True),
        ),
    ]
