# Generated by Django 5.0.6 on 2024-06-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_appointment_options_consultation_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='species',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
