# Generated by Django 5.0.6 on 2024-07-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_consultation_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetAssociatedInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=20)),
                ('location_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vet',
            name='services',
            field=models.CharField(choices=[('CONSULTATION', 'CONSULTATION'), ('SURGERY', 'SURGERY'), ('CLINICAL EXAMINATION', 'CLINICAL EXAMINATION'), ('OBSTETRICAL EXAMINATION', 'OBSTETRICAL EXAMINATION'), ('NUTRITION ANALYSIS AND FORMULATION', 'NUTRITION ANALYSIS AND FORMULATION')], default='CLINICAL EXAMINATION', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='vet',
            name='associated_institutions',
            field=models.ManyToManyField(blank=True, to='base.vetassociatedinstitution'),
        ),
    ]
