# Generated by Django 5.0.6 on 2024-07-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_vetassociatedinstitution_vet_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet',
            name='associated_institutions',
        ),
        migrations.DeleteModel(
            name='VetAssociatedInstitution',
        ),
    ]
