# Generated by Django 5.0.6 on 2024-07-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_vet_associated_institutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='licence_no',
            field=models.CharField(default='xxxxxxxxxxxxxx', max_length=20),
        ),
    ]
