# Generated by Django 5.0.6 on 2024-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_vet_licence_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='salutation',
            field=models.CharField(choices=[('Dr', 'DOCTOR'), ('Prof', 'PROFESSOR')], default='Dr', max_length=5),
        ),
    ]
