# Generated by Django 5.0.6 on 2024-07-07 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_user_middle_name_user_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationBackgroundDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50)),
                ('joined', models.DateField()),
                ('exited', models.DateField()),
                ('qualification', models.CharField(choices=[('K.C.P.E', 'K.C.P.E'), ('K.C.S.E', 'K.C.S.E'), ('CERTIFICATE', 'CERTIFICATE'), ('DIPLOMA', 'DIPLOMA'), ('DEGREE', 'DEGREE'), ('MASTERS DEGREE', 'MASTERS DEGREE'), ('Phd', 'Phd')], max_length=20)),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vet')),
            ],
        ),
        migrations.AddField(
            model_name='vet',
            name='education_background',
            field=models.ManyToManyField(blank=True, null=True, related_name='vet_education_background', to='base.educationbackgrounddetail'),
        ),
    ]
