# Generated by Django 5.0.6 on 2024-07-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_educationbackgrounddetail_vet_education_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='education_background',
            field=models.ManyToManyField(blank=True, related_name='vet_education_background', to='base.educationbackgrounddetail'),
        ),
    ]
