# Generated by Django 5.0.6 on 2024-07-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_vetassociatedinstitution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetassociatedinstitution',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
