# Generated by Django 5.0.6 on 2024-07-07 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_vetassociatedinstitution_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetassociatedinstitution',
            name='vet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vet'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='associated_institutions',
            field=models.ManyToManyField(blank=True, related_name='vet_associated_institutions', to='base.vetassociatedinstitution'),
        ),
    ]
