# Generated by Django 5.0.6 on 2024-07-13 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_vetassociatedinstitution_vet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet',
            name='associated_institutions',
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=20)),
                ('location_description', models.TextField()),
                ('role', models.CharField(max_length=50, null=True)),
                ('worked_from', models.DateField()),
                ('worked_to', models.DateField(blank=True, null=True)),
                ('referees', models.TextField()),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vet')),
            ],
        ),
        migrations.AddField(
            model_name='vet',
            name='vet_portfolio',
            field=models.ManyToManyField(blank=True, related_name='portfolio_for_vet', to='base.portfolio'),
        ),
        migrations.DeleteModel(
            name='VetAssociatedInstitution',
        ),
    ]
