# Generated by Django 5.0.6 on 2024-07-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_remove_vet_associated_institutions_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='vet_portfolio',
            field=models.ManyToManyField(blank=True, related_name='vet_portfolio', to='base.portfolio'),
        ),
    ]
