# Generated by Django 5.0.6 on 2024-07-13 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_vet_vet_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=20)),
                ('location_description', models.TextField()),
                ('specialization', models.CharField(choices=[('SA', 'SMALL ANIMALS'), ('LA', 'LARGE ANIMALS'), ('BIRDS', 'POULTRY'), ('SA && LA', 'SMALL ANIMALS AND LARGE ANIMALS')], max_length=10)),
                ('services', models.CharField(choices=[('CONSULTATION', 'CONSULTATION'), ('SURGERY', 'SURGERY'), ('CLINICAL EXAMINATION', 'CLINICAL EXAMINATION'), ('OBSTETRICAL EXAMINATION', 'OBSTETRICAL EXAMINATION'), ('NUTRITION ANALYSIS AND FORMULATION', 'NUTRITION ANALYSIS AND FORMULATION')], max_length=50)),
                ('images', models.ImageField(default='avatar.svg', null=True, upload_to='posted_images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='educationbackgrounddetail',
            options={'ordering': ['-joined']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-worked_from']},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='vet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_associated_portfolio', to='base.vet'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
