# Generated by Django 5.0.6 on 2024-07-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_vetclinic_alter_educationbackgrounddetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('VET', 'Vet'), ('APP USER', 'App User')], default='ADMIN', max_length=12),
        ),
    ]
