# Generated by Django 5.0.6 on 2024-07-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_vetuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='start_practice',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
