# Generated by Django 5.0.6 on 2024-07-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_vet_start_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='start_practice',
            field=models.DateField(),
        ),
    ]
