# Generated by Django 5.0.6 on 2024-07-28 05:18

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_vet_start_practice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.user',),
            managers=[
                ('app_users', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='vet',
            name='licence_expired',
            field=models.BooleanField(default=True),
        ),
    ]
