# Generated by Django 5.0.6 on 2024-07-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_appuser_alter_vet_licence_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['scheduled_date', 'scheduled_time_from'], 'permissions': [('dg_view_appointment', 'OLP Can View Permission')]},
        ),
    ]
