# Generated by Django 5.0.6 on 2024-07-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['scheduled_date', 'scheduled_time_from'], 'permissions': [('dg_view_appointment', 'OLP Can View Appointment')]},
        ),
    ]
