# Generated by Django 5.0.6 on 2024-07-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='licence_no',
            field=models.CharField(default='xxxxxxxxxxxxxx', max_length=20, unique=True),
        ),
    ]
