# Generated by Django 5.0.6 on 2024-07-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_alter_vet_licence_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='licence_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
