# Generated by Django 5.0.6 on 2024-07-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_vet_licence_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('VET', 'Vet'), ('APPUSER', 'App User')], default='ADMIN', max_length=12),
        ),
    ]
