# Generated by Django 5.0.6 on 2024-07-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created'], 'permissions': [('dg_view_consultation', 'OLP Can View Consultation')]},
        ),
    ]
