# Generated by Django 5.0.6 on 2024-07-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_consultation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created'], 'permissions': [('dg_view_consultation', 'OLP Can View Consultation'), ('request_consultation', 'Can Request Consultation')]},
        ),
    ]
