# Generated by Django 5.0.6 on 2024-07-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_alter_consultation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['scheduled_date', 'scheduled_time_from'], 'permissions': [('dg_view_appointment', 'OLP Can View Appointment'), ('request_appointment', 'Can Request Appointment'), ('approve_appointment', 'Can Approve Appointment')]},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created'], 'permissions': [('dg_view_consultation', 'OLP Can View Consultation'), ('request_consultation', 'Can Request Consultation'), ('approve_consultation', 'Can Approve Consultation')]},
        ),
    ]
