# Generated by Django 5.0.6 on 2024-07-31 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_appointment_vet_alter_consultation_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetcomment',
            name='vet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commented_on_vet', to=settings.AUTH_USER_MODEL),
        ),
    ]
