# Generated by Django 5.0.6 on 2024-07-31 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_vetcomment_vet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vetcomment',
            options={'ordering': ['-updated', '-created'], 'permissions': [('dg_view_comment', 'OLP Can View Comment')]},
        ),
    ]
