# Generated by Django 5.0.6 on 2024-08-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_alter_vetcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='vet_speciality',
            field=models.CharField(choices=[('SMALL ANIMALS', 'SMALL ANIMALS'), ('LARGE ANIMALS', 'LARGE ANIMALS'), ('POULTRY', 'POULTRY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vetclinic',
            name='specialization',
            field=models.CharField(choices=[('SMALL ANIMALS', 'SMALL ANIMALS'), ('LARGE ANIMALS', 'LARGE ANIMALS'), ('POULTRY', 'POULTRY')], max_length=20),
        ),
    ]
