# Generated by Django 5.0.6 on 2024-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_alter_vet_vet_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='services',
            field=models.CharField(choices=[('Consultation', 'CONSULTATION'), ('Surgery', 'SURGERY'), ('Clinical Services', 'CLINICAL SERVICES'), ('Obstetrical Services', 'OBSTETRICAL SERVICES'), ('Nutrition Analysis', 'NUTRITION ANALYSIS'), ('Feed Formulation', 'FEED FORMULATION')], default='CLINICAL EXAMINATION', max_length=50),
        ),
        migrations.AlterField(
            model_name='vetclinic',
            name='services',
            field=models.CharField(choices=[('Consultation', 'CONSULTATION'), ('Surgery', 'SURGERY'), ('Clinical Services', 'CLINICAL SERVICES'), ('Obstetrical Services', 'OBSTETRICAL SERVICES'), ('Nutrition Analysis', 'NUTRITION ANALYSIS'), ('Feed Formulation', 'FEED FORMULATION')], max_length=50),
        ),
    ]
