# Generated by Django 5.0.6 on 2024-08-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_vet_services_alter_vetclinic_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='services',
            field=models.CharField(choices=[('Consultation', 'CONSULTATION'), ('Surgery', 'SURGERY'), ('Clinical Services', 'CLINICAL SERVICES'), ('Obstetrical Services', 'OBSTETRICAL SERVICES'), ('Nutrition Analysis', 'NUTRITION ANALYSIS'), ('Feed Formulation', 'FEED FORMULATION')], default='Clinical Services', max_length=50),
        ),
    ]
