# Generated by Django 5.0.6 on 2024-08-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_vet_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'MOMBASA'), ('Nairobi', 'NAIROBI'), ('Trans-Nzoia', 'TRANS-NZOIA'), ('West Pokot', 'WEST POKOT'), ('Marakwet', 'MARAKWET'), ('Isiolo', 'ISIOLO'), ('Kericho', 'KERICHO'), ('Uasin-Gishu', 'UASIN-GISHU')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.CharField(choices=[('Kitale', 'KITALE'), ('Eldoret', 'ELDORET'), ('Mombasa', 'Mombasa'), ('Nairobi', 'NAIROBI'), ('Kericho', 'KERICHO'), ('Kapenguria', 'KAPENGURIA'), ('Iten', 'ITEN'), ('Isiolo', 'ISIOLO')], max_length=20, null=True),
        ),
    ]
