# Generated by Django 5.0.6 on 2024-08-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_user_county_alter_user_town'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vet',
            options={'ordering': ['licence_expired', '-successfull_consultations', '-consultations', 'start_practice']},
        ),
    ]
