# Generated by Django 5.0.6 on 2024-08-04 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_vet_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSatisfactionComment',
            fields=[
                ('vetcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.vetcomment')),
                ('satisfied', models.BooleanField()),
            ],
            bases=('base.vetcomment',),
        ),
        migrations.RemoveField(
            model_name='vetcomment',
            name='is_satisfaction_comment',
        ),
    ]
