# Generated by Django 5.0.6 on 2024-08-04 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_consultationsatisfactioncomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsatisfactioncomment',
            name='consultationobject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.consultation'),
        ),
    ]
