# Generated by Django 5.0.6 on 2024-08-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_consultationsatisfactioncomment_consultationobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsatisfactioncomment',
            name='satisfied',
            field=models.CharField(choices=[('Satisfied', 'SATISFIED'), ('Not Satisfied', 'NOT SATISFIED')], default='Satisfied', max_length=15),
        ),
    ]
