# Generated by Django 5.0.6 on 2024-08-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_alter_consultationsatisfactioncomment_satisfied'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationsatisfactioncomment',
            options={'ordering': ['-updated', '-created'], 'permissions': [('dg_view_consultationcomment', 'OLP Can View ConsultationComment')]},
        ),
    ]
