# Generated by Django 5.0.6 on 2024-12-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_consultationsatisfactioncomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationsatisfactioncomment',
            options={'ordering': ['-updated', '-created'], 'permissions': [('dg_view_consultationcomment', 'OLP Can View ConsultationComment'), ('dg_can_leave_comment_for_vet', 'OLP Can Leave Comment For Vet')]},
        ),
        migrations.RemoveField(
            model_name='consultationsatisfactioncomment',
            name='satisfied',
        ),
        migrations.AddField(
            model_name='consultationsatisfactioncomment',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vet',
            name='client_rating',
            field=models.IntegerField(default=0),
        ),
    ]
