# Generated by Django 5.0.6 on 2024-12-16 11:00

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_alter_consultationsatisfactioncomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsatisfactioncomment',
            name='rate',
            field=models.IntegerField(default=0, validators=[base.validators.rate_validation]),
        ),
    ]
