# Generated by Django 5.0.6 on 2024-12-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_alter_consultationsatisfactioncomment_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationsatisfactioncomment',
            old_name='rate',
            new_name='rate_vet',
        ),
    ]
