# Generated by Django 5.0.6 on 2024-12-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_rename_rate_consultationsatisfactioncomment_rate_vet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vet',
            options={'ordering': ['licence_expired', 'start_practice', '-consultations', '-client_rating']},
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='client_satisfied',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='successfull_consultations',
        ),
    ]
