# Generated by Django 5.0.6 on 2024-12-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_alter_vet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vet',
            options={'ordering': ['licence_expired', '-client_rating', 'start_practice']},
        ),
        migrations.AddField(
            model_name='vet',
            name='successfull_consultations',
            field=models.IntegerField(default=0),
        ),
    ]
