# Generated by Django 5.0.6 on 2024-12-17 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_alter_vet_options_vet_successfull_consultations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vet',
            options={'ordering': ['licence_expired', '-successfull_consultations', '-client_rating', 'start_practice']},
        ),
        migrations.AddField(
            model_name='consultation',
            name='paid_for',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='vet',
        ),
        migrations.CreateModel(
            name='ConsultationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.consultationfee')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulting_vet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='vet',
            field=models.ManyToManyField(related_name='vets_consulted', to=settings.AUTH_USER_MODEL),
        ),
    ]
