# Generated by Django 5.0.6 on 2024-12-17 11:19

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_alter_vet_options_consultation_paid_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[base.validators.validate_amount]),
        ),
    ]
