# Generated by Django 5.0.6 on 2024-12-27 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_alter_consultationfee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='secondary_consultants',
            field=models.ManyToManyField(related_name='vets_consulted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='vet',
        ),
        migrations.AddField(
            model_name='consultation',
            name='vet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_consulted', to=settings.AUTH_USER_MODEL),
        ),
    ]
