# Generated by Django 5.0.6 on 2024-12-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_consultation_secondary_consultants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationfee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
