# Generated by Django 5.0.6 on 2024-12-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='referral_colleagues',
            field=models.ManyToManyField(related_name='referral_colleagues', to='base.vetuser'),
        ),
    ]
