# Generated by Django 5.0.6 on 2024-12-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_vet_referral_colleagues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='secondary_consultants',
            field=models.ManyToManyField(related_name='vets_consulted', to='base.vetuser'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='vet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_consulted', to='base.vetuser'),
        ),
    ]
