# Generated by Django 5.0.6 on 2024-12-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_alter_consultation_secondary_consultants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralColleagueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING')], default='PENDING', max_length=8)),
                ('colleague_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_colleague', to='base.vetuser')),
                ('requesting_vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_vet', to='base.vetuser')),
            ],
        ),
    ]
