# Generated by Django 5.0.6 on 2024-12-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_referralcolleaguerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralcolleaguerequest',
            options={'ordering': ['-timestamp'], 'permissions': [('dg_view_colleague_request', 'OLP Can View Colleague Request'), ('dg_confirm_colleague_request', 'OLP Can Confirm Colleague Request')]},
        ),
    ]
