# Generated by Django 5.0.6 on 2024-12-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_alter_referralcolleaguerequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='referral_colleagues',
            field=models.ManyToManyField(blank=True, related_name='referral_colleagues', to='base.vetuser'),
        ),
    ]
