# Generated by Django 5.0.6 on 2024-12-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_alter_vet_referral_colleagues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp'], 'permissions': [('dg_view_notification', 'OLP Can View Notification')]},
        ),
    ]
