# Generated by Django 5.0.6 on 2024-12-31 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('dg_edit_user_profile', 'OLP Can Edit User Profile')]},
        ),
    ]
