# Generated by Django 5.0.6 on 2024-12-31 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.vetuser'),
        ),
    ]
