# Generated by Django 5.0.6 on 2025-01-01 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_alter_vet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsatisfactioncomment',
            name='consultationobject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.consultation'),
        ),
    ]
