# Generated by Django 5.0.6 on 2025-04-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_alter_consultationsatisfactioncomment_consultationobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationfee',
            name='mpesa_transaction_code',
            field=models.CharField(default='xxxxxxxxxx', max_length=10),
        ),
        migrations.AddField(
            model_name='consultationfee',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationfee',
            name='transaction_id',
            field=models.CharField(default='xxxxxxxxxxxxx', max_length=13),
        ),
    ]
