# Generated by Django 5.0.6 on 2025-04-13 11:57

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_consultationfee_mpesa_transaction_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationfee',
            name='payment_number',
            field=models.CharField(max_length=13, null=True, validators=[base.validators.validatePhoneNumber]),
        ),
        migrations.AlterField(
            model_name='consultationfee',
            name='transaction_id',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
