# Generated by Django 5.0.6 on 2025-04-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_consultationfee_payment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='consultation_fee',
            field=models.IntegerField(default=1),
        ),
    ]
