# Generated by Django 5.1 on 2026-02-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0086_vet_consultation_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("STAFF", "Staff"),
                    ("Vets", "Veterinarians"),
                    ("Users", "Regular Users"),
                ],
                default="ADMIN",
                max_length=12,
            ),
        ),
    ]
