# Generated by Django 5.1 on 2026-02-15 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0087_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationfee",
            name="consultation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.consultation",
            ),
        ),
    ]
