# Generated by Django 5.1 on 2026-02-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0037_all_enhancements"),
        ("base", "0088_alter_consultationfee_consultation"),
    ]

    operations = []
